CREATE TABLE IF NOT EXISTS gemstone (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(100) NOT NULL,
    stone_type VARCHAR(50),
    carat DECIMAL(10,2) NOT NULL,
    quality VARCHAR(50),
    base_price DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_gemstone_name ON gemstone(name);
