-- simple cart per user
CREATE TABLE IF NOT EXISTS cart (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id BIGINT NOT NULL,
                                    status VARCHAR(20) DEFAULT 'OPEN',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- items inside a cart
CREATE TABLE IF NOT EXISTS cart_item (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         cart_id BIGINT NOT NULL,
                                         gemstone_id BIGINT NOT NULL,
                                         quantity INT NOT NULL,
                                         unit_price DECIMAL(12,2) NOT NULL,     -- snapshot price from gemstone.base_price
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_item_gem FOREIGN KEY (gemstone_id) REFERENCES gemstone(id) ON DELETE RESTRICT,
    CONSTRAINT uq_cart_item UNIQUE (cart_id, gemstone_id) -- one row per gem in a cart
    );

CREATE INDEX IF NOT EXISTS idx_cart_user ON cart(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_cart ON cart_item(cart_id);
